version: "3"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - .:/BookshopMbicycle
    env_file:
      - db_keys.txt
    ports:
      - "8000:8000"
    depends_on:
      - db1
      - redis
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'

  db1:
    image: postgres:latest
    container_name: postgres2
    env_file:
      - db_keys.txt

  adminer:
    image: adminer
    container_name: admin_db
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis_db1

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_w
    volumes:
      - .:/BookshopMbicycle
    env_file:
      - db_keys.txt
    depends_on:
      - redis
    ports:
      - '5555:5555'
    command: bash -c 'celery -A BookshopMbicycle worker -l info -B -E'